name-template: "$NEXT_MINOR_VERSION"
tag-template: "$NEXT_MINOR_VERSION"
change-template: '- $TITLE #$NUMBER [@$AUTHOR]'

exclude-labels:
  - "changelog: skip"

template: |

  https://pillow.readthedocs.io/en/stable/releasenotes/$NEXT_MINOR_VERSION.html

  ## Changes

  $CHANGES
