dist: xenial
language: python
cache: pip

notifications:
  irc: "chat.freenode.net#pil"

# Run fast lint first to get fast feedback.
# Run slow PyPy next, to give it a headstart and reduce waiting time.
# Run latest 3.x next, to get quick compatibility results.
# Then run the remainder.

matrix:
  fast_finish: true
  include:
    - python: "3.8"
      arch: arm64
    - python: "3.7"
      arch: arm64
    - python: "3.6"
      arch: arm64
    - python: "3.5"
      arch: arm64

    - python: "3.8"
      arch: ppc64le
    - python: "3.7"
      arch: ppc64le
    - python: "3.6"
      arch: ppc64le
    - python: "3.5"
      arch: ppc64le

    - python: "3.8"
      arch: s390x
    - python: "3.7"
      arch: s390x
    - python: "3.6"
      arch: s390x
    - python: "3.5"
      arch: s390x

    - python: "3.6"
      name: "Lint"
      env: LINT="true"
    - python: "pypy3"
      name: "PyPy3 Xenial"
    - python: "3.8"
      name: "3.8 Xenial"
      services: xvfb
    - python: '3.7'
      name: "3.7 Xenial"
      services: xvfb
    - python: '3.6'
      name: "3.6 Xenial PYTHONOPTIMIZE=1"
      env: PYTHONOPTIMIZE=1
      services: xvfb
    - python: '3.5'
      name: "3.5 Xenial PYTHONOPTIMIZE=2"
      env: PYTHONOPTIMIZE=2
      services: xvfb

install:
  - |
    if [ "$LINT" == "true" ]; then
      pip install tox
    else
      .travis/install.sh;
    fi

script:
- |
  if [ "$LINT" == "true" ]; then
    tox -e lint
  else
    .travis/build.sh
    .travis/test.sh
  fi

after_success:
- |
  if [ "$LINT" == "" ]; then
    .travis/after_success.sh
  fi
