language: python

# for python-qt4
virtualenv:
  system_site_packages: true

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"

install: 
  - "sudo apt-get -qq install libfreetype6-dev liblcms2-dev libwebp-dev python-qt4 ghostscript libffi-dev"
  - "pip install cffi"
  - "apt-get install python-tk"


script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - python selftest.py
  - python Tests/run.py

matrix:
  allow_failures:
    - python: "pypy"
