dist: xenial
language: python
cache: pip

notifications:
  irc: "chat.freenode.net#pil"

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      arch: arm64
    - python: "3.7"
      arch: ppc64le
    - python: "3.8"
      arch: s390x

install:
  - |
    .ci/install.sh;

script:
  - |
    .ci/build.sh
    .ci/test.sh

after_success:
  - |
    .ci/after_success.sh
