language: python

# for python-qt4
virtualenv:
  system_site_packages: true

python:
#  - 2.6
  - 2.7
#  - 3.2
#  - 3.3
#  - "pypy"

install: 
  - "sudo apt-get -qq install libfreetype6-dev liblcms2-dev python-qt4 ghostscript libffi-dev cmake"
  - "pip install cffi"
  # enables pypy to compile
 # - "sudo apt-get install python-tk"

  # webp  UNDONE -- refactor
  - "wget 'https://webp.googlecode.com/files/libwebp-0.4.0.tar.gz' -O /tmp/libwebp-0.4.0.tar.gz"
  - "tar -C /tmp -xvzf /tmp/libwebp-0.4.0.tar.gz"
  - "pushd /tmp/libwebp-0.4.0 && ./configure --prefix=/usr --enable-libwebpmux --enable-libwebpdemux && make && sudo make install && popd"

  - "wget 'https://openjpeg.googlecode.com/files/openjpeg-2.0.0.tar.gz' -O /tmp/openjpeg-2.0.0.tar.gz"
  - "tar -C /tmp -xvzf /tmp/openjpeg-2.0.0.tar.gz"
  - "pushd /tmp/openjpeg-2.0.0 && cmake . && make && sudo DESTDIR=/usr make install && popd"

script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - python selftest.py
  - python Tests/run.py

#matrix:
#  allow_failures:
#    - python: "pypy"
