name: Test Windows

on: [push, pull_request]

jobs:
  build:
  
    runs-on: windows-2016
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5", "3.6", "3.7", "pypy3.6"]
        architecture: ["x86", "x64"]
        include:
          - architecture: "x86"
            platform-vcvars: "x86"
            platform-msbuild: "Win32"
          - architecture: "x64"
            platform-vcvars: "x86_amd64"
            platform-msbuild: "x64"
          - python-version: "pypy3.6"
            pypy-version: "pypy-c-jit-97588-7392d01b93d0-win32"
            pypy-url: "http://buildbot.pypy.org/nightly/py3.6/pypy-c-jit-97588-7392d01b93d0-win32.zip"
            # pypy-url: "https://bitbucket.org/pypy/pypy/downloads/${{ matrix.pypy-version }}.zip"
        exclude:
          - python-version: "pypy3.6"
            architecture: "x64"
    timeout-minutes: 30
    
    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}
    
    steps:
    - uses: actions/checkout@v1

    - name: Install PyPy
      if: "contains(matrix.python-version, 'pypy')"
      run: |
        curl -fsSL -o pypy3.zip "${{ matrix.pypy-url }}"
        7z x pypy3.zip "-o$env:RUNNER_WORKSPACE\"
        mv "$env:RUNNER_WORKSPACE\${{ matrix.pypy-version }}" "$env:RUNNER_WORKSPACE\${{ matrix.python-version }}"
        $env:PYTHON="$env:RUNNER_WORKSPACE\${{ matrix.python-version }}"
        # set env: pythonLocation
        Write-Host "`#`#[set-env name=pythonLocation;]$env:PYTHON" # old syntax https://github.com/actions/toolkit/issues/61
        Write-Host "::set-env name=pythonLocation::$env:PYTHON" # new syntax https://github.com/actions/toolkit/blob/5bb77ec03fea98332e41f9347c8fbb1ce1e48f4a/docs/commands.md
        New-Item -ItemType SymbolicLink -Path "$env:PYTHON\python.exe" -Target "$env:PYTHON\pypy3.exe"
        curl -fsSL -o get-pip.py https://bootstrap.pypa.io/get-pip.py
        & $env:PYTHON\python.exe get-pip.py
      shell: pwsh

    # sets env: pythonLocation
    - name: Set up Python
      if: "!contains(matrix.python-version, 'pypy')"
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    
    - name: Fetch dependencies
      run: |
        $env:PYTHON=$env:pythonLocation
        curl -fsSL -o pillow-depends.zip https://github.com/python-pillow/pillow-depends/archive/master.zip
        7z x pillow-depends.zip -oc:\
        mv c:\pillow-depends-master c:\pillow-depends
        xcopy c:\pillow-depends\*.zip $env:GITHUB_WORKSPACE\winbuild\
        xcopy c:\pillow-depends\*.tar.gz $env:GITHUB_WORKSPACE\winbuild\
        xcopy /s c:\pillow-depends\test_images\* $env:GITHUB_WORKSPACE\tests\images\
        cd $env:GITHUB_WORKSPACE/winbuild/
        python.exe $env:GITHUB_WORKSPACE\winbuild\build_dep.py
        # .\build_deps.cmd
      env:
        EXECUTABLE: bin\python.exe
      shell: pwsh

    - name: Build dependencies / libjpeg
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\jpeg-9c
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        nmake -nologo -f makefile.vc setup-vc6
        nmake -nologo -f makefile.vc clean
        nmake -nologo -f makefile.vc nodebug=1 libjpeg.lib
        copy /Y /B j*.h %INCLIB%
        copy /Y /B *.lib %INCLIB%

    - name: Build dependencies / zlib
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\zlib-1.2.11
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        nmake -nologo -f win32\Makefile.msc clean
        nmake -nologo -f win32\Makefile.msc zlib.lib
        copy /Y /B z*.h %INCLIB%
        copy /Y /B *.lib %INCLIB%
        copy /Y /B zlib.lib %INCLIB%\z.lib

    - name: Build dependencies / libtiff
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\tiff-4.0.10
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        copy %GITHUB_WORKSPACE%\winbuild\nmake.opt nmake.opt
        nmake -nologo -f makefile.vc clean
        nmake -nologo -f makefile.vc lib
        copy /Y /B libtiff\tiff*.h %INCLIB%
        copy /Y /B libtiff\*.dll %INCLIB%
        copy /Y /B libtiff\*.lib %INCLIB%

    - name: Build dependencies / webp
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\libwebp-1.0.3
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        rmdir /S /Q output\release-static
        nmake -nologo -f Makefile.vc CFG=release-static RTLIBCFG=static OBJDIR=output ARCH=${{ matrix.architecture }} all
        mkdir %INCLIB%\webp
        copy /Y /B src\webp\*.h %INCLIB%\webp
        copy /Y /B output\release-static\${{ matrix.architecture }}\lib\* %INCLIB%

    - name: Build dependencies / freetype
      run: |
        REM Toolkit v100 not available; missing VCTargetsPath; Clean fails

        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\freetype-2.10.1
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        rmdir /S /Q objs
        set DefaultPlatformToolset=v140
        set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets
        set MSBUILD="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
        %MSBUILD% builds\windows\vc2010\freetype.sln /t:Build /p:Configuration="Release" /p:Platform=${{ matrix.platform-msbuild }} /m
        xcopy /Y /E /Q include %INCLIB%
        copy /Y /B objs\${{ matrix.platform-msbuild }}\Release\freetype.dll %INCLIB%
        copy /Y /B objs\${{ matrix.platform-msbuild }}\Release\freetype.lib %INCLIB%

    - name: Build dependencies / lcms2
      if: false
      run: |
        REM Projects\VC2015\lcms2.sln is not available in lcms2-2.7

        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\lcms2-2.7
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        rmdir /S /Q Lib
        rmdir /S /Q Projects\VC2015\Release
        set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets
        set MSBUILD="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
        %MSBUILD% Projects\VC2015\lcms2.sln /t:Clean;lcms2_static /p:Configuration="Release" /p:Platform=${{ matrix.platform-msbuild }} /m
        xcopy /Y /E /Q include %INCLIB%
        copy /Y /B Lib\MS\*.lib %INCLIB%

    - name: Build dependencies / openjpeg
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\openjpeg-2.3.1msvcr10-x32
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        cmake.exe -DBUILD_THIRDPARTY:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" .
        nmake -nologo -f Makefile clean
        nmake -nologo -f Makefile
        mkdir %INCLIB%\openjpeg-2.3.1
        copy /Y /B src\lib\openjp2\*.h %INCLIB%\openjpeg-2.3.1
        copy /Y /B bin\*.lib %INCLIB%

    - name: Build dependencies / ghostscript
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        set BUILD=%GITHUB_WORKSPACE%\winbuild\build
        cd /D %BUILD%\ghostscript-9.27
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        echo on
        set MSVC_VERSION=14
        set RCOMP="C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\RC.Exe"
        if "${{ matrix.architecture }}"=="x64" set WIN64=""
        nmake -nologo -f psi\msvc.mak
        rem Add bin to PATH variable: Copy to INCLIB, then add INCLIB to PATH in Test step.
        copy /Y /B bin\* %INCLIB%

    - name: Build Pillow
      run: |
        set PYTHON=%pythonLocation%
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include
        set MPLSRC=%GITHUB_WORKSPACE%
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        cd /D %GITHUB_WORKSPACE%
        set DISTUTILS_USE_SDK=1
        set LIB=%INCLIB%;%PYTHON%\tcl
        set INCLUDE=%INCLIB%;%GITHUB_WORKSPACE%\depends\tcl86\include;%INCLUDE%
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }} 8.1
        set BLDOPT=install
        %PYTHON%\%EXECUTABLE% setup.py build_ext --add-imaging-libs=msvcrt install
        %PYTHON%\%EXECUTABLE% -c "from PIL import _webp;import os, shutil;shutil.copy(r'%INCLIB%\freetype.dll', os.path.dirname(_webp.__file__));"
        %PYTHON%\%EXECUTABLE% selftest.py --installed
      env:
        EXECUTABLE: python.exe

    - name: pip install pytest pytest-cov codecov
      run: |
        "%pythonLocation%\python.exe" -m pip install pytest pytest-cov
        pip install codecov
    
    - name: Test Pillow
      run: |
        set PYTHON=%pythonLocation%
        set INCLIB=%GITHUB_WORKSPACE%\winbuild\depends\msvcr10-x32
        rem Add GhostScript executables (copied to INCLIB) to PATH.
        path %INCLIB%;%PATH%
        cd /D %GITHUB_WORKSPACE%
        %PYTHON%\python.exe -m pytest -vx --cov PIL --cov-report term --cov-report xml Tests
    
    - name: Upload coverage
      run: 'codecov --file "%GITHUB_WORKSPACE%\coverage.xml" --name "%pythonLocation%"'
      env:
        CODECOV: Scripts\codecov.exe
    
